### PR TITLE
Switch data.table to Imports

### PR DESCRIPTION
**Pull request by MichaelChirico**
Depends are discouraged for data.table:

https://github.com/Rdatatable/data.table/issues/3076

(in fact, we hope that R will eventually deprecate this mode of dependency)

Since you already use `import(data.table)` in your NAMESPACE, the change is trivial -- we would only need to update usages in examples, vignettes and tests that use data.table calls unqualified.

PS I tried running your test suite but got a lot of failures apparently unrelated to data.table.

### CODE REVIEW

**Comment by MichaelChirico** [comment]
I propose an even better solution in the second commit: I used {lintr} to find that you only use one function from {data.table}, namely `data.table()`, so using a very strict `importFrom()` approach is best.

```r
dt_exports <- getNamespaceExports("data.table")
dt_functions <- grep("^[a-zA-Z]", dt_exports, value=TRUE)
dt_operators <- grep("^[%]", dt_exports, value=TRUE)
lintr::lint_package(linters = list(
  lintr::undesirable_function_linter(setNames(nm = dt_functions)),
  lintr::undesirable_operator_linter(setNames(nm = dt_operators))
))
```

**Comment by Brauckhoff** [comment]
Thank you for your contributions to improve the quality of the package. Your changes will be incorporated.

Could you please provide details on the failed tests you encountered, this information could help me refine the code further or did the adjustment to importFrom rectify the problems mentioned in the first post?

**Comment by MichaelChirico** [comment]
The only failure is that the vignette assumes {data.table} is attached (because it was in Depends), without {data.table} attached this fails:

https://github.com/Brauckhoff/biopixR/blob/428bd8acbd73a57efc2b31694eeeec33bcd53be4/vignettes/biopixR.Rmd#L726

So I added `library(data.table)`, but we could also make that `data.table::data.table()`, e.g.

**Comment by Brauckhoff** [comment]
Thank you for explaining the situation. I will keep the code in the form you provided, making sure the library() indicates the use of your package.

**Pull request merged**
